sudo: false

language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.3
 - 3.4
 - 3.5

install:
 - pip install pillow
 - pip install coveralls

script:
 - coverage run --source=piexif setup.py test

after_success:
  coveralls

matrix:
  fast_finish: true
