sudo: false

language: python

python:
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - 3.7

install:
 - pip install pillow==5.0.0
 - pip install coveralls

script:
 - coverage run --source=piexif setup.py test

after_success:
  coveralls

matrix:
  fast_finish: true
